name: .NET CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Dodaj ten krok przed budowaniem projektu
    - name: Set Version Suffix
      run: echo "VersionSuffix=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build
    - name: Deploy to Development
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'mwoapp'
        slot-name: 'development'
        publish-profile: ${{ secrets.SECRET_MWOAPP }}
        package: ./bin/Release/net7.0/publish/wwwroot # Ścieżka do zbudowanej aplikacji

